Update cloudflare api to fix removed field
nrdxp/cfdyndns pull request #60
Opened 2024-06-14 01:53 UTC by Wyn-Price

A patch for cloudflare/cloudflare-rs/pull/240
Fixes #57

I've included @jcgruenhage's make-owner-fields-optional changes in my cloudflare-rs PR.

Removes some unused imports that no longer exist (`ApiClient`), and the change in `api.rs` is to coerce the error type from `Client::new`, as I'm assuming they're now returning their own error type. I can make this nicer if you want.

I can confirm that this works with `A` records, I haven't tested with `AAAA` records but I can't see why it wouldn't also work.

<details>
<summary>Before:</summary>

```
$ cargo run -- --records x.wynprice.com --token XXX
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/cfdyndns --records x.wynprice.com --token XXX`
 INFO  cfdyndns::ip > ...
Error: error decoding response body: missing field `multiple_railguns_allowed` at line 1 column 586
```
</details>

<details>
<summary>After - when there is no change needed:</summary>

```
$ cargo run -- --records x.wynprice.com --token XXX
   Compiling cfdyndns v0.2.0 (/home/wp/programming/cfdyndns)
    Finished dev [unoptimized + debuginfo] target(s) in 4.37s
     Running `target/debug/cfdyndns --records x.wynprice.com --token XXX`
 INFO  cfdyndns::ip > ...
 INFO  cfdyndns::dns > skipping A record `x.wynprice.com`; already up to date
```
</details>

<details>
<summary>After - when the DNS record needs changing:</summary>

```
$ cargo run -- --records x.wynprice.com --token XXX
   Compiling cfdyndns v0.2.0 (/home/wp/programming/cfdyndns)
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/cfdyndns --records x.wynprice.com --token XXX`
 INFO  cfdyndns::ip > ...
 INFO  cfdyndns::dns > request: x.wynprice.com (... → ...)
```
</details>

2024-06-28 18:14 UTC, nrdxp commented
looks like the build is failing in CI

2024-06-28 18:24 UTC, Wyn-Price commented
Yup, I can have a look at it tonight.

2024-06-29 18:54 UTC, Wyn-Price commented
I reran crate2nix, hopefully that's what the problem was. It seems to have changed the format of `crate-hashes.json` (even though the version of `crate2nix` was the same) ,but hopefully that's fine.

2024-06-29 19:01 UTC, nrdxp requested changes
Looks good to me. Thanks for the fix. I would just request you maybe squash the first two commits of the PR into one, and it should be ready to merge.

2024-06-29 19:05 UTC, Wyn-Price commented
Sure, done

2024-06-29 19:12 UTC, nrdxp approved these changes

2024-06-29 19:16 UTC, merged

2024-06-29 20:27 UTC, Wyn-Price commented
I'm happy to update nixpkgs if you create a new release

2024-06-29 23:58 UTC, nrdxp commented
tagged as v0.2.1